**<font size="6">Title of Project</font>**

Women Cloth Reviews Prediction with Multi Nomial Naives Bayes

**<font size="4">Objective</font>**

To develop a predictive model using Multi- Nomial Naive Bayes that accurately classifies women's clothing reviews into categories such as positive, negative, or neutral sentiment, thereby providing valuable insights into customer opinions and enhancing decision-making for fashion retailers.

**<font size="4">Import Library</font>**

In [6]:
import numpy as np
import pandas as pd

**<font size="4">Import Data</font>**

In [8]:
df = pd.read_csv("https://raw.githubusercontent.com/YBIFoundation/ProjectHub-MachineLearning/main/Women%20Clothing%20E-Commerce%20Review.csv")

**<font size="4">Describe Data</font>**

In [12]:
df.describe()

Clothing ID           Age        Rating   Recommended  \
count  23486.000000  23486.000000  23486.000000  23486.000000   
mean     918.118709     43.198544      4.196032      0.822362   
std      203.298980     12.279544      1.110031      0.382216   
min        0.000000     18.000000      1.000000      0.000000   
25%      861.000000     34.000000      4.000000      1.000000   
50%      936.000000     41.000000      5.000000      1.000000   
75%     1078.000000     52.000000      5.000000      1.000000   
max     1205.000000     99.000000      5.000000      1.000000   

       Positive Feedback  
count       23486.000000  
mean            2.535936  
std             5.702202  
min             0.000000  
25%             0.000000  
50%             1.000000  
75%             3.000000  
max           122.000000

**<font size="4">Data Visualization</font>**

In [10]:
df.head()

Clothing ID  Age                    Title  \
0          767   33                      NaN   
1         1080   34                      NaN   
2         1077   60  Some major design flaws   
3         1049   50         My favorite buy!   
4          847   47         Flattering shirt   

                                              Review  Rating  Recommended  \
0  Absolutely wonderful - silky and sexy and comf...       4            1   
1  Love this dress!  it's sooo pretty.  i happene...       5            1   
2  I had such high hopes for this dress and reall...       3            0   
3  I love, love, love this jumpsuit. it's fun, fl...       5            1   
4  This shirt is very flattering to all due to th...       5            1   

   Positive Feedback        Division Department   Category  
0                  0       Initmates   Intimate  Intimates  
1                  4         General    Dresses    Dresses  
2                  0         General    Dresses    Dresses  
3                  0  General Petite    Bottoms      Pants  
4                  6         General       Tops    Blouses

In [11]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 23486 entries, 0 to 23485
Data columns (total 10 columns):
 #   Column             Non-Null Count  Dtype 
---  ------             --------------  ----- 
 0   Clothing ID        23486 non-null  int64 
 1   Age                23486 non-null  int64 
 2   Title              19676 non-null  object
 3   Review             22641 non-null  object
 4   Rating             23486 non-null  int64 
 5   Recommended        23486 non-null  int64 
 6   Positive Feedback  23486 non-null  int64 
 7   Division           23472 non-null  object
 8   Department         23472 non-null  object
 9   Category           23472 non-null  object
dtypes: int64(5), object(5)
memory usage: 1.8+ MB


In [13]:
df.shape

(23486, 10)

**<font size="4">Data Preprocessing</font>**

In [15]:
df.isna().sum()

Clothing ID             0
Age                     0
Title                3810
Review                845
Rating                  0
Recommended             0
Positive Feedback       0
Division               14
Department             14
Category               14
dtype: int64

In [16]:
df[df['Review']=='']

Empty DataFrame
Columns: [Clothing ID, Age, Title, Review, Rating, Recommended, Positive Feedback, Division, Department, Category]
Index: []

In [17]:
df['Review'].fillna('No Review',inplace=True)

C:\Users\aggar\AppData\Local\Temp\ipykernel_19316\3226930775.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Review'].fillna('No Review',inplace=True)


In [18]:
df.isna().sum()

Clothing ID             0
Age                     0
Title                3810
Review                  0
Rating                  0
Recommended             0
Positive Feedback       0
Division               14
Department             14
Category               14
dtype: int64

**<font size="4">Define Target Variable (Y) and Feature Variables (X)</font>**

In [20]:
X = df['Review']

In [21]:
Y = df['Rating']

In [22]:
df['Rating'].value_counts()

Rating
5    13131
4     5077
3     2871
2     1565
1      842
Name: count, dtype: int64

**<font size="4">Train Test Split</font>**

In [24]:
from sklearn.model_selection import train_test_split

In [25]:
X_train,X_test,Y_train,Y_test=train_test_split(X,Y,train_size=0.7,stratify = Y,random_state=42)

In [26]:
X_train.shape,X_test.shape,Y_train.shape,Y_test.shape

((16440,), (7046,), (16440,), (7046,))

In [27]:
from sklearn.feature_extraction.text import CountVectorizer

cv = CountVectorizer(lowercase=True, analyzer='word', ngram_range=(2, 3), stop_words='english', max_features=50000)
x_train = cv.fit_transform(X_train)
cv.get_feature_names_out()

array(['00 fits', '00 petite', '00 regular', ..., 'zipper tried',
       'zipper wouldn', 'zippered pockets'], dtype=object)

In [28]:
x_train.toarray()

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [29]:
x_test = cv.fit_transform(X_test)
cv.get_feature_names_out()

array(['00 bought', '00p fit', '0p brand', ..., 'zipper nice',
       'zipper short', 'zippers buttons'], dtype=object)

In [30]:
x_test.toarray()

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

**<font size="4">Modeling</font>**

In [32]:
from sklearn.naive_bayes import MultinomialNB

model = MultinomialNB()
model.fit(x_train, Y_train)

MultinomialNB()

**<font size="4">Model Prediction</font>**

In [34]:
y_pred = model.predict(x_test)
y_pred.shape

(7046,)

In [35]:

y_pred

array([5, 2, 5, ..., 1, 1, 2], dtype=int64)

In [36]:
model.predict_proba(x_test)

array([[6.21015754e-02, 9.13462918e-02, 7.36485813e-02, 1.97337414e-01,
        5.75566137e-01],
       [3.40099257e-01, 5.56737432e-01, 1.02634448e-01, 4.87832428e-04,
        4.10302628e-05],
       [3.58272506e-02, 6.66058394e-02, 1.22262774e-01, 2.16180049e-01,
        5.59124088e-01],
       ...,
       [5.04291598e-01, 2.00671123e-02, 2.65639527e-01, 2.09911402e-01,
        9.03610502e-05],
       [6.90202198e-01, 2.20229257e-01, 8.66589669e-02, 2.82900355e-03,
        8.05746132e-05],
       [4.29341929e-02, 4.35679328e-01, 4.25615329e-01, 4.72253081e-02,
        4.85458421e-02]])

**<font size="4">Model Evaluation</font>**

In [38]:
from sklearn.metrics import confusion_matrix, classification_report
print(confusion_matrix(Y_test, y_pred))

[[  77   42   45   34   55]
 [ 153   94   63   72   88]
 [ 286  202  131  102  140]
 [ 509  312  215  214  273]
 [1263  731  598  557  790]]


In [39]:
classification_report(Y_test, y_pred)

'              precision    recall  f1-score   support\n\n           1       0.03      0.30      0.06       253\n           2       0.07      0.20      0.10       470\n           3       0.12      0.15      0.14       861\n           4       0.22      0.14      0.17      1523\n           5       0.59      0.20      0.30      3939\n\n    accuracy                           0.19      7046\n   macro avg       0.21      0.20      0.15      7046\nweighted avg       0.40      0.19      0.23      7046\n'

In [40]:
report = classification_report(Y_test, y_pred, output_dict=True)

In [41]:
df_report = pd.DataFrame(report).transpose()

In [42]:
print(df_report)

              precision    recall  f1-score      support
1              0.033654  0.304348  0.060606   253.000000
2              0.068067  0.200000  0.101567   470.000000
3              0.124525  0.152149  0.136958   861.000000
4              0.218590  0.140512  0.171063  1523.000000
5              0.586924  0.200559  0.298959  3939.000000
accuracy       0.185353  0.185353  0.185353     0.185353
macro avg      0.206352  0.199513  0.153831  7046.000000
weighted avg   0.396328  0.185353  0.229793  7046.000000


Explanation:

1. Context: In the world of fashion and e-commerce, understanding customer sentiment is crucial for businesses to make informed decisions. Customer reviews play a vital role in gauging the popularity and satisfaction levels of products.

2. Objective: The primary goal of this machine learning project is to build a predictive model that can automatically classify women's clothing reviews based on their sentiment. Sentiment analysis helps identify whether a review is positive, negative, or neutral.

3. Methodology: The chosen methodology for this project is the Multi-Nomial Naive Bayes algorithm. Naive Bayes is a probabilistic classification algorithm that works well with text data, making it suitable for sentiment analysis.

4. Data Collection: To train and evaluate the model, a dataset of women's clothing reviews will be collected. This dataset will ideally consist of text reviews and corresponding sentiment labels (positive, negative, or neutral) provided by customers.

5. Data Preprocessing: Before feeding the data into the model, it will undergo preprocessing steps. This includes tasks such as text tokenization, removing stop words, and transforming the text into numerical features that the algorithm can work with.

6. Model Training: The Multi-Nomial Naive Bayes model will be trained on a portion of the dataset. During training, the algorithm learns the patterns and relationships between words and sentiments in the reviews.

7. Model Evaluation: To assess the model's performance, it will be tested on a separate dataset (not used during training). Common evaluation metrics include accuracy, precision, recall, and F1-score.

8. Deployment: Once the model proves to be accurate and reliable, it can be deployed for real-time sentiment analysis of women's clothing reviews. This can be integrated into an e-commerce website or used for regular analysis of customer feedback.

9. Benefits: The project's outcomes include providing fashion retailers with valuable insights into customer opinions, helping them identify areas of improvement, popular products, and overall customer satisfaction levels. It can also assist in decision-making related to inventory management, marketing strategies, and product development.

10. Future Enhancements: Depending on the project's success, future enhancements could involve incorporating more advanced natural language processing techniques, expanding the model to handle multiclass classification, or adapting it for other product categories.

11. In summary, this project aims to leverage machine learning, specifically Multi-Nomial Naive Bayes, to automate sentiment analysis of women's clothing reviews, enabling businesses to make data-driven decisions and enhance customer satisfaction.